version: 1.0.{build}
image: Visual Studio 2019

branches:
  only:
    - master

build_script:
  - ps: dotnet build -c Debug ./Tooling/Tooling.csproj
  - ps: dotnet build -c Release ./Tooling/Tooling.csproj
  - ps: dotnet tool install --global StyleCop.Analyzers
  - ps: dotnet tool run stylecop analyze -c Debug ./Tooling/Tooling.csproj
  - ps: dotnet test -c Debug ./Tooling.Tests/Tooling.Tests.csproj

test_script:
  - ps: dotnet test -c Debug ./Tooling.Tests/Tooling.Tests.csproj
